server:
  # Jetty Web Server
  applicationConnectors:
    - type: http
      port: 8080
      idleTimeout: 120s
  adminConnectors:
    - type: http
      port: 8081
      idleTimeout: 120s
  requestLog:
    appenders: []

# Database settings.
database:
  driverClass: org.h2.Driver
  user: "sa"
  #  password:
  url: jdbc:h2:mem:revolut;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
# Healthcheck
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSS"

      # Do not display log statements below this threshold to stdout.
      threshold: ALL

      # Write to stdout or stderr
      target: stdout

      # A custom Logback format string.
      logFormat: "level=\"%p\" timestamp=\"%d{ISO8601,UTC}Z\" category=\"%c\" %replace(%m){'\"password\":\"(.*)\"', '\"password\":\"\"'}%n%xEx"
      # The timezone used to format dates (use UTC)
      timeZone: UTC

    - type: file

      # Do not write log statements below this threshold to the file.
      threshold: ALL

      # The file to which current statements will be logged.
      currentLogFilename: ./logs/moneytransfer.log

      # Logback's Size and Time Based Rolling Policy
      archivedLogFilenamePattern: ./logs/moneytransfer-%d{yyyy-MM-dd}-%i.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # Max log file size before rolling over.
      maxFileSize: 150MB

      # The timezone used to format dates (use UTC)
      timeZone: UTC

      # A custom Logback format string.
      logFormat: "level=\"%p\" timestamp=\"%d{ISO8601,UTC}Z\" category=\"%c\" %replace(%m){'\"password\":\"(.*)\"', '\"password\":\"\"'}%n%xEx"
